configuration:
  template_dir:
  - "git://github.com/moremoban/pypi-mobans.git?submodule=true&brach=master!/statics"
  - "git://github.com/moremoban/pypi-mobans.git?branch=dev&submodule=true!/templates"
  - ".moban.d"
  configuration: pypifs.yml
targets:
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/conf.py_t"
  - "pypifs/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - Pipfile: Pipfile.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
  - README.rst: CUSTOM_README.rst.jj2
  - ".github/workflows/pythonpublish.yml": "pythonpublish.yml"
