requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    branch: dev
    submodule: true
configuration:
  template_dir:
  - "pypi-mobans:templates"
  - ".moban.d"
  configuration: pypifs.yml
targets:
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/conf.py_t"
  - "pypifs/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
  - Pipfile: Pipfile.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
